"""create all tables

Revision ID: 8de2ff128b55
Revises: 
Create Date: 2025-11-21 19:55:14.174979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de2ff128b55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_node_type', sa.Enum('INPUT', 'OUTPUT', 'TRANSFORMATION', name='node_type', native_enum=False), nullable=False),
    sa.Column('end_node_type', sa.Enum('INPUT', 'OUTPUT', 'TRANSFORMATION', name='node_type', native_enum=False), nullable=False),
    sa.Column('start_node', sa.Integer(), nullable=False),
    sa.Column('end_node', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('flow_id')
    )
    op.create_table('inputs',
    sa.Column('input_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('broker_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('input_id')
    )
    op.create_index(op.f('ix_inputs_name'), 'inputs', ['name'], unique=True)
    op.create_table('outputs',
    sa.Column('output_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('broker_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_index(op.f('ix_outputs_name'), 'outputs', ['name'], unique=True)
    op.create_table('pipelines',
    sa.Column('pipeline_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_id')
    )
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('transformations',
    sa.Column('transformation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_in', sa.JSON(), nullable=True),
    sa.Column('schema_out', sa.JSON(), nullable=True),
    sa.Column('python_script', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('transformation_id')
    )
    op.create_index(op.f('ix_transformations_name'), 'transformations', ['name'], unique=True)
    op.create_table('pipeline_flows',
    sa.Column('pipeline_flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_flow_id')
    )
    op.create_index(op.f('ix_pipeline_flows_flow_id'), 'pipeline_flows', ['flow_id'], unique=False)
    op.create_index(op.f('ix_pipeline_flows_pipeline_id'), 'pipeline_flows', ['pipeline_id'], unique=False)
    op.create_table('pipeline_inputs',
    sa.Column('pipeline_input_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.input_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_input_id')
    )
    op.create_index(op.f('ix_pipeline_inputs_input_id'), 'pipeline_inputs', ['input_id'], unique=False)
    op.create_index(op.f('ix_pipeline_inputs_pipeline_id'), 'pipeline_inputs', ['pipeline_id'], unique=False)
    op.create_table('pipeline_outputs',
    sa.Column('pipeline_output_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.output_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_output_id')
    )
    op.create_index(op.f('ix_pipeline_outputs_output_id'), 'pipeline_outputs', ['output_id'], unique=False)
    op.create_index(op.f('ix_pipeline_outputs_pipeline_id'), 'pipeline_outputs', ['pipeline_id'], unique=False)
    op.create_table('pipeline_tags',
    sa.Column('pipeline_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_tag_id')
    )
    op.create_index(op.f('ix_pipeline_tags_pipeline_id'), 'pipeline_tags', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_tags_tag_id'), 'pipeline_tags', ['tag_id'], unique=False)
    op.create_table('pipeline_transformations',
    sa.Column('pipeline_transformation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.pipeline_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.transformation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_transformation_id')
    )
    op.create_index(op.f('ix_pipeline_transformations_pipeline_id'), 'pipeline_transformations', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_transformations_transformation_id'), 'pipeline_transformations', ['transformation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_transformations_transformation_id'), table_name='pipeline_transformations')
    op.drop_index(op.f('ix_pipeline_transformations_pipeline_id'), table_name='pipeline_transformations')
    op.drop_table('pipeline_transformations')
    op.drop_index(op.f('ix_pipeline_tags_tag_id'), table_name='pipeline_tags')
    op.drop_index(op.f('ix_pipeline_tags_pipeline_id'), table_name='pipeline_tags')
    op.drop_table('pipeline_tags')
    op.drop_index(op.f('ix_pipeline_outputs_pipeline_id'), table_name='pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_outputs_output_id'), table_name='pipeline_outputs')
    op.drop_table('pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_inputs_pipeline_id'), table_name='pipeline_inputs')
    op.drop_index(op.f('ix_pipeline_inputs_input_id'), table_name='pipeline_inputs')
    op.drop_table('pipeline_inputs')
    op.drop_index(op.f('ix_pipeline_flows_pipeline_id'), table_name='pipeline_flows')
    op.drop_index(op.f('ix_pipeline_flows_flow_id'), table_name='pipeline_flows')
    op.drop_table('pipeline_flows')
    op.drop_index(op.f('ix_transformations_name'), table_name='transformations')
    op.drop_table('transformations')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_outputs_name'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_inputs_name'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_table('flows')
    # ### end Alembic commands ###
