"""schema to schemas

Revision ID: 454ce252085a
Revises: 8de2ff128b55
Create Date: 2025-11-24 14:19:43.903197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454ce252085a'
down_revision: Union[str, Sequence[str], None] = '8de2ff128b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('schemas', sa.JSON(), nullable=True))
    op.drop_column('inputs', 'schema')
    op.add_column('outputs', sa.Column('schemas', sa.JSON(), nullable=True))
    op.drop_column('outputs', 'schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('outputs', 'schemas')
    op.add_column('inputs', sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('inputs', 'schemas')
    # ### end Alembic commands ###
